### PR TITLE
Update main.go

### LINKED ISSUE #36: This workspace has been deleted.
Getting alerts for valid Slack instances but when I visit the URL it says `This workspace has been deleted.` Or `suspended.`

### PR DESCRIPTION
**Pull request by geeknik**
Fixes #36

### CODE REVIEW

**Comment by 0xblackbird** [comment]
Hi @geeknik! Thank you for your contributions! I will look into this and get back to you as soon as I can!

**Comment by geeknik** [comment]
Sure, no worries. If you like this patch, I'll have some more just like it. I'm digging the tool, but there are a few issues regarding valid matching. 👍🏻

**Comment by 0xblackbird** [comment]
In that case a more robust fix would be the way forward (such as using dynamic exclusion rules) instead of using if-statements.

Do you have any further examples of false positives that you can share? Thank you!

**Comment by 0xblackbird** [comment]
The latest release v1.12.0 (#38) should fix this issue. I've added a new optional "exclusionPattern" to the template properties to exclude false positive results.

Feel free to create a new PR with an updated template definition file! ;)

Thanks a lot again for your contributions!!

**Comment by 0xblackbird** [comment]
The latest release v1.12.0 (https://github.com/intigriti/misconfig-mapper/pull/38) should fix this issue. I've added a new optional "exclusionPattern" to the template properties to exclude false positive results.

Feel free to create a new PR with an updated template definition file! ;)

Thanks a lot again for your contributions!!

**Pull request closed without merging**
